### ISSUE TITLE
🐛 Designer Review - Use the correct icons on the "Contact Us" component, and transition on hover

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website-v3#115]
- [ ] Use the correct icons on the "Contact Us" component and implement icon transition on hover

    ![Image](https://user-images.githubusercontent.com/25432120/216486625-27605946-ac48-495e-a258-77c1f98c3ba0.png)
**Figure: New site with arrows icon + missing hover animation**

    ![Image](https://user-images.githubusercontent.com/25432120/216486658-d6210345-1b48-4771-9ef4-9529c2d9f3e0.png)
**Figure: Current site with chevron icon + hover animation**

**Comment by wicksipedia** [comment]
As per conversation with @2fernandez - hover animation on the accordion icon is overkill
