### ISSUE TITLE
🎨 Designer Review - round 2

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website-v3#138]
Once all the designer review items are complete - get another review in preparation for go live

**Comment by tiagov8** [comment]
Hey @BrookJeynes 

1. BUG - see the ON AIR banner at the top... text is outside the banner area
   <img width="1386" alt="Screenshot 2023-02-16 at 12 32 59 PM" src="https://user-images.githubusercontent.com/12601228/219480902-6cbb305a-152d-4cd8-a0ce-4e7e7c809f47.png">

2. UI - Make the navigation squares in the carrousel bigger and closer to each other (use current site as reference)
   <img width="792" alt="Screenshot 2023-02-16 at 12 34 18 PM" src="https://user-images.githubusercontent.com/12601228/219481046-498cdf20-3d1e-44cd-9c6d-e2c21ba57cda.png">

3. UI -Make "CONSULTING" and "CORE SERVICES" font a bit smaller (use current site as reference)
4. UI - Improve the "More services..." button style (current site as reference)
    Note: Same for "More events"
   <img width="324" alt="Screenshot 2023-02-16 at 12 36 30 PM" src="https://user-images.githubusercontent.com/12601228/219481404-a5b15def-c15a-4eb0-ba0c-f99127758fad.png">

5. UI - Remove padding between thumbs (blue) + Add padding on the right (orange)
   <img width="561" alt="Screenshot 2023-02-16 at 12 38 21 PM" src="https://user-images.githubusercontent.com/12601228/219482092-8659bbfa-45cb-4657-950b-079147f825f9.png">

6. UI - Change the red text to be black 
   PS. I know this is coming from the current site, but I don't like the red in there. We can try to improve this area later on
<img width="421" alt="Screenshot 2023-02-16 at 12 40 28 PM" src="https://user-images.githubusercontent.com/12601228/219482325-e46d20af-fee2-4009-9e64-8b59e3f6497a.png">

7. UX - On the new site I can't tell this is a video (we need the play button)
   <img width="508" alt="Screenshot 2023-02-16 at 12 42 42 PM" src="https://user-images.githubusercontent.com/12601228/219482471-b99f58ab-309d-493b-96d7-4e56f0a69fe3.png">

8. UI - The current site is 1170px wide, the new one is 1120px... any reason to lose the 50px? I would prefer to increase than decrease, but it is safer to keep the same.
   <img width="1425" alt="Screenshot 2023-02-16 at 12 44 11 PM" src="https://user-images.githubusercontent.com/12601228/219482839-543c717d-95ae-49e6-b212-76e137bdd2ac.png">
   <img width="1414" alt="Screenshot 2023-02-16 at 12 44 25 PM" src="https://user-images.githubusercontent.com/12601228/219482842-1a72c4ed-0bc2-4cd5-aebf-7d5d35e2092b.png">

9 UI - Footer - Add the separator between the 2 lines + make font bigger (use current site as reference)
   <img width="1290" alt="Screenshot 2023-02-16 at 12 48 09 PM" src="https://user-images.githubusercontent.com/12601228/219483485-394c2778-715a-4975-91eb-cbb7c6a1852f.png">

**Comment by bradystroud** [comment]
> 1. BUG - see the ON AIR banner at the top... text is outside the banner area

@tiagov8 already have an issue for this 
#184

**Comment by tiagov8** [comment]
Hey guys, 1 more... after checking with designers we agreed:

7. ...the text should be center aligned instead of justified on Related Technologies boxes

   <img width="377" alt="Screenshot 2023-02-16 at 4 36 14 PM" src="https://user-images.githubusercontent.com/12601228/219519941-edbec3df-1e22-4dab-a730-fc23cabdc5bc.png">

**Comment by BrookJeynes** [comment]
The following PBIs have been created to cover these responses:
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/190
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/191
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/192
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/193
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/194
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/196
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/197
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/198
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/202
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/203
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/204
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/204
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/205

**Comment by bradystroud** [comment]
Closing as the feedback tasks have moved to new issues
