### ISSUE TITLE
📃 Content - re-sync consulting content

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website-v3#139]
There may have been content changes since we last pulled the markdown files.

Update as content as necessary

**Comment by BrookJeynes** [comment]
The following items were created based on the issues found in this issue:
- https://github.com/SSWConsulting/SSW.Website-v3/issues/160
- https://github.com/SSWConsulting/SSW.Website-v3/issues/161
- https://github.com/SSWConsulting/SSW.Website-v3/issues/162
- https://github.com/SSWConsulting/SSW.Website-v3/issues/163
- https://github.com/SSWConsulting/SSW.Website-v3/issues/164
- https://github.com/SSWConsulting/SSW.Website-v3/issues/165

**Comment by wicksipedia** [comment]
closing as work is being done in the linked issues
