### ISSUE TITLE
🐛 Consulting Page - Fix Technology card Images

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website-v3#148]
![Image](https://user-images.githubusercontent.com/17246482/217676586-a45af20c-ca9e-4f72-919f-d758e947f275.png)

- [ ] Fix React Native image
- [ ] ~~Can we configure a build error if images aren't available? Investigate (Timebox to a 2)~~

**Comment by jimmidier** [comment]
Moving second task into #157
