### ISSUE TITLE
📃 Content - re-sync consulting content

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website-v3#159]
This issue is a reminder to double check content before going live

Should not be done until we have a go-live target date

**Comment by BrookJeynes** [comment]
The following items were created based on the issues found in this issue:
- https://github.com/SSWConsulting/SSW.Website-v3/issues/160
- https://github.com/SSWConsulting/SSW.Website-v3/issues/161
- https://github.com/SSWConsulting/SSW.Website-v3/issues/162
- https://github.com/SSWConsulting/SSW.Website-v3/issues/163
- https://github.com/SSWConsulting/SSW.Website-v3/issues/164

**Comment by Harry-Ross** [comment]
Just created this issue:

#271
