### ISSUE TITLE
💄 Consulting pages - Broken images

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website-v3#160]
There are a bunch of broken images on the consultation pages, typically in regards to the tech cards.

- [x] fix broken images on artificial-intelligence page
    ![image](https://user-images.githubusercontent.com/25432120/217952004-c7fa60a8-2f69-4f00-92fc-e726a297cb40.png)
    **Figure: Broken tech card image**
- [x] fix broken images on chinafy page
    ![image](https://user-images.githubusercontent.com/25432120/217956181-48ad95dd-c899-4900-b66f-9c6f94100ef4.png)
    **Figure: Broken tech card images**
- [x] fix broken images on hololens page
    ![image](https://user-images.githubusercontent.com/25432120/217956343-641f6247-9a50-4050-a18a-33c6ab8c5689.png)
    **Figure: Broken tech card images**
- [x] fix broken images on kubernetes page
    ![image](https://user-images.githubusercontent.com/25432120/217956895-af48a8f1-1e19-49ac-8edf-27d1b899c789.png)
    **Figure: Broken tech card images**
- [x] fix broken images on mobile application development page
    ![image](https://user-images.githubusercontent.com/25432120/217957743-dc0e3583-783e-4b3f-821b-3afc6913b335.png)
    **Figure: Broken tech card images**
    ![image](https://user-images.githubusercontent.com/25432120/217957789-8a78b3d8-3455-46ff-a8dd-e9361229277c.png)
    **Figure: Broken tech card images**
    ![image](https://user-images.githubusercontent.com/25432120/217957922-c467af6a-947a-45c7-bb3e-df6ca25fe63a.png)
    **Figure: Wrong logo on tech card**
- [x] fix broken images on remote work page
    ![image](https://user-images.githubusercontent.com/25432120/217958275-10163910-ad52-4b27-b14d-661b94938f07.png)
    **Figure: Broken tech card images**
    ![image](https://user-images.githubusercontent.com/25432120/217958300-e1eadfce-6d4f-497a-ac9f-cb0b0c8b20a3.png)
    **Figure: Broken tech card images**
    ![image](https://user-images.githubusercontent.com/25432120/217958324-1116256c-61d1-4f92-bcb3-a2a376661b05.png)
    **Figure: Broken tech card images**
- [x] fix broken images on windows desktop apps page
    ![image](https://user-images.githubusercontent.com/25432120/217958693-14f05c06-1525-487b-87f2-e8c1e147ac7a.png)
    **Figure: Broken tech card images**
- [x] fix broken images on scrum page
    ![image](https://user-images.githubusercontent.com/25432120/217958987-ba5e91a3-51fd-4b90-84f6-5e8cddafa189.png)
    **Figure: broken image**
- [x] fix broken images on pay per click page
    ![image](https://user-images.githubusercontent.com/25432120/217959111-ec051aa6-3523-4251-a435-3bf393f5f729.png)
    **Figure: broken image**
- [x] fix broken images on remote work page
    ![image](https://user-images.githubusercontent.com/25432120/217959317-23169348-0655-4045-853f-86b41a68e189.png)
    **Figure: broken image**

**Comment by tkapa** [comment]
> * [x]  fix broken images on chinafy page
>   ![image](https://user-images.githubusercontent.com/25432120/217956181-48ad95dd-c899-4900-b66f-9c6f94100ef4.png)
>   **Figure: Broken tech card images**


For Chinafy, the page doesn't actually have Images on it. I've updated the Tech component to allow components without Images

**Comment by tkapa** [comment]
It seems like we must define a width and height for the Image in the technology component, which ends up with the stretched out images. It isn't ideal
