### ISSUE TITLE
💄 Consulting pages - Security page broken list

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website-v3#163]
- [x] The items within the "Identify Solutions" section are in a list

![image](https://user-images.githubusercontent.com/25432120/217962327-5466ef8f-d18f-4036-9869-3aed05fe5693.png)
**Figure: Items inline instead of a list**

**Comment by johnxussw** [comment]
![image](https://user-images.githubusercontent.com/113034339/218912619-1ca0532e-4f42-40fc-a697-4dedb0d3b96c.png)
**Figure: https://ssw.com.au/consulting/security**

![image](https://user-images.githubusercontent.com/113034339/218912699-9aa55aa6-cb82-41ac-aef4-cb0d2cdd4f03.png)
**Figure: https://ssw.com.au/ssw/consulting/security.aspx**
