### ISSUE TITLE
💄UI - "Call Us" button underlined black

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website-v3#239]
![image](https://user-images.githubusercontent.com/20507092/220010121-d4dcd003-6a11-4598-b3f7-1fa1e0319168.png)
**Figure: underlined "call us" button**

Not sure what caused this, but it happened to the live banner bar as well - other link tags on the site may also be affected:

- [ ] Apply the "unstyled" class to the appropriate element, which removes the text's underline
- [ ] Investigate if there are any other link buttons that have been affected

**Comment by wicksipedia** [comment]
Unable to repro - @Harry-Ross can repro this on prod?
If not, close the issue
