### ISSUE TITLE
📝 Docs - Make this project follow Awesome Documentation

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Website-v3#52]
Hi @bradystroud ,

I noticed this repo is not following the SSW awesome documentation rule
https://www.ssw.com.au/rules/awesome-documentation/

1. Please update it to follow the rule

**Acceptance Criteria**
All 8 documents exist and are populated

**Comment by tkapa** [comment]
Hey @pierssinclairssw,

> 1. Please update it to follow the rule
Done - You can see the documentation in the [repository Wiki](https://github.com/SSWConsulting/SSW.Website-v3/wiki)
