### ISSUE TITLE
⚡ PageSpeed Insights | Address Performance Issues

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website-v3#59]
Even after attempting to implement NextJs/Script features, it seems that PageSpeed Insights isn't getting much better.

Using PageSpeed Insights as a reference, fix performance hits.

- [ ] ⚡ PageSpeed Insights | Address Performance Issues

_Originally posted by @tkapa in https://github.com/SSWConsulting/SSW.Website-v3/issues/54#issuecomment-1399807339_

**Comment by wicksipedia** [comment]
Understand that the perf is in the realms of acceptable for zendesk but I think we could do better.

Possible speed improvement for zendesk - https://www.newmediacampaigns.com/blog/maintaining-great-site-performanc-using-zendesk-web-widget

**Comment by JackDevAU** [comment]
Might be good to investigate upgrading to NextJS v13 + react 18. To be able to use some of the new lazy loading features! 

Note: Some of these features are still experimental, so there is some risk involved. 

Checkout:
https://nextjs.org/docs/advanced-features/dynamic-import
https://nextjs.org/docs/advanced-features/react-18/overview
