### ISSUE TITLE
🐛 Layout - fix content width

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website-v3#72]
Logos should be in 1 line for desktop

![Image](https://user-images.githubusercontent.com/600044/215368463-292d83ff-85dc-4416-95da-f7cc2b5fd246.png)

**Comment by jimmidier** [comment]
@wicksipedia Shall we make the logos responsive on small screen?
e.g.
![image](https://user-images.githubusercontent.com/16027480/215383075-38e87528-1f2f-4726-825a-adcca474576f.png)

**Comment by wicksipedia** [comment]
I think the images just need to be centered of justified when responsive.
Splitting them over 3 lines is ok
