### ISSUE TITLE
⚡ Tina - upgrade to iframe implementation

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website-v3#91]
https://tina.io/blog/upgrading-to-iframe/

**Comment by BrookJeynes** [comment]
After talking with "jpohalloran (Product Manager)" in the Tina Discord, it seems that the migration warning is a bug.



![Image](https://user-images.githubusercontent.com/25432120/216471676-a779dee1-3059-4d2a-9084-3e966943999f.png)

**Comment by bradystroud** [comment]
Closing as this has already been done
