### ISSUE TITLE
🐛 Tina - Tina throwing error on Firefox

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website-v3#95]
## Info
An error appears when using the website on Firefox. However, the error can be dismissed and nothing seems to be broken past that point.

## Steps to repro

1. Go to https://app-sswwebsite.azurewebsites.net

## Expected

No error appears

## Actual

An error appears

![image](https://user-images.githubusercontent.com/25432120/216473575-b7ed8674-6e2d-471c-a67a-87b54093488f.png)
**Figure: Error message**

**Comment by bradystroud** [comment]
Couldn't reproduce
