### ISSUE TITLE
Tina Cloud - Move to SSW account

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#99]
```[tasklist]
### Tasks
- [x] Create account
- [x] Configure repo access
- [x] Add secrets
- [x] Setup SSO
- [x] Record video on how to create content on the new site
```

**Comment by tkapa** [comment]
Hey @wicksipedia,

I know that we're on the way to getting a license sorted out.

Anything we can do to add the account to Keeper and set up the Tine Cloud secrets so that we're ready for when it goes live?

**Comment by wicksipedia** [comment]
@leahy268 is sorting this out... its TBA atm

**Comment by leahy268** [comment]
Sorry guys.  The account is available.  It has been shared now in Keeper -> External Services

Let me know if you need anything - At this stage as far as we know it is only for internal use mind.

**Comment by tkapa** [comment]
@leahy268 

I think we'll probably hold off on switching over until we have confirmation

**Comment by wicksipedia** [comment]
closing as this as #711 is now tracking the video (last remaning bit)
